accelerator: gpu
devices: 1
max_epochs: 100
strategy: auto
enable_checkpointing: False
# callbacks:
#   # Checkpointing
#   - class_path: lightning.pytorch.callbacks.ModelCheckpoint
#     init_args:
#       monitor: val_loss
#       mode: min
#       save_top_k: 1
#       verbose: True
#   # Early stopping
#   - class_path: lightning.pytorch.callbacks.EarlyStopping
#     init_args:
#       monitor: val_loss
#       mode: min
#       patience: 10
#       verbose: True
#   # Performance logging
#   - class_path: ssl_tools.callbacks.performance.PerformanceLogger
#     init_args: {}