data: /workspaces/hiaac-m4/data/standartized_balanced/KuHar
input_size: 360
hidden_size: 128
num_hidden_layers: 1
num_classes: 6
transforms: identity
experiment_name: model_train
dataset_name: KuHar
accelerator: gpu
devices: 1
max_epochs: 1
batch_size: 32
log_dir: ./mlruns