data: /workspaces/hiaac-m4/data/standartized_balanced/KuHar
in_channels: 6
dim_feedforward: 60
num_classes: 6
heads: 1
num_layers: 1
log_dir: ./mlruns
experiment_name: test
batch_size: 64
max_epochs: 1
accelerator: gpu
devices: 1
model_name: transformer